/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/* This file is automatically generated using bindtool */

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <pmtf/string.hpp>
// pydoc.h is automatically generated in the build directory
// #include <pmt_pydoc.h>

void bind_string(py::module& m)
{
    using string = pmtf::string;

    py::class_<string, std::shared_ptr<string>>(m, "string")

        .def(py::init<const std::string&>())

        ;
}
