FROM fedora:42

RUN sudo dnf upgrade -y && \
  sudo dnf install -y \
  gcc-c++ \
  clang \
  meson \
  ninja-build \
  cmake \
  make \
  python3-devel \
  gtest-devel \
  cli11-devel \
  git \
  fmt-devel \
  pybind11-devel
